base_url = "https://www.teckie1.com"
title = "Teckie1"
theme = "terminimal"
default_language = "en"

compile_sass = true
build_search_index = false

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
logo_text = "teckie1"
logo_home_link = "/"
author = "Michael Mcknight"
accent_color = "blue"
background_color = "dark"
menu_items = [
    {name = "blog", url = "$BASE_URL"},
    {name = "about", url = "$BASE_URL/about"},
    {name = "github", url = "https://github.com/teckie-1", newtab = true},
]
page_titles = "combined"
